"""Add app schema

Revision ID: 0b24786ba344
Revises: 96d44567c544
Create Date: 2026-08-25 22:13:02.987662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b24786ba344'
down_revision: Union[str, Sequence[str], None] = '96d44567c544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS app")

    op.execute("""
               ALTER TABLE public.categories
                   SET SCHEMA app
               """)

    op.execute("""
               ALTER TABLE public.products
                   SET SCHEMA app
               """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE app.products
        SET SCHEMA public
    """)

    op.execute("""
        ALTER TABLE app.categories
        SET SCHEMA public
    """)

