"""add rating column to ProductModel

Revision ID: 650e0bf41ca9
Revises: f9f85e0ec207
Create Date: 2026-09-11 23:27:30.080892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650e0bf41ca9'
down_revision: Union[str, Sequence[str], None] = 'f9f85e0ec207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'rating', schema='app')
    # ### end Alembic commands ###
