"""Create CartItem model

Revision ID: 68b860cca66e
Revises: 6d4faa5bdcb0
Create Date: 2026-09-25 21:00:14.185689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b860cca66e'
down_revision: Union[str, Sequence[str], None] = '6d4faa5bdcb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['app.products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_cart_items_product_id'), 'cart_items', ['product_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_cart_items_user_id'), 'cart_items', ['user_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_cart_items_user_id'), table_name='cart_items', schema='app')
    op.drop_index(op.f('ix_app_cart_items_product_id'), table_name='cart_items', schema='app')
    op.drop_table('cart_items', schema='app')
    # ### end Alembic commands ###
