"""Create Search Vector

Revision ID: 6d4faa5bdcb0
Revises: e08662492b43
Create Date: 2026-09-17 22:18:14.350263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d4faa5bdcb0'
down_revision: Union[str, Sequence[str], None] = 'e08662492b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("\n            setweight(to_tsvector('english', coalesce(name, '')), 'A')\n            || \n            setweight(to_tsvector('english', coalesce(description, '')), 'B')\n            ", persisted=True), nullable=False), schema='app')
    op.create_index('ix_products_tsv_gin', 'products', ['tsv'], unique=False, schema='app', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_tsv_gin', table_name='products', schema='app', postgresql_using='gin')
    op.drop_column('products', 'tsv', schema='app')
    # ### end Alembic commands ###
