"""Add user model

Revision ID: 6ef36536ae6d
Revises: 0b24786ba344
Create Date: 2026-09-05 20:36:28.829799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef36536ae6d'
down_revision: Union[str, Sequence[str], None] = '0b24786ba344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("DELETE FROM app.products")

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_users_email'), 'users', ['email'], unique=True, schema='app')
    op.add_column('products', sa.Column('seller_id', sa.Integer(), nullable=False), schema='app')
    op.create_foreign_key(None, 'products', 'users', ['seller_id'], ['id'], source_schema='app', referent_schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', schema='app', type_='foreignkey')
    op.drop_column('products', 'seller_id', schema='app')
    op.drop_index(op.f('ix_app_users_email'), table_name='users', schema='app')
    op.drop_table('users', schema='app')
    # ### end Alembic commands ###
