"""add product columns updated_at and created_at 

Revision ID: e08662492b43
Revises: 215277700cd4
Create Date: 2026-09-14 20:06:51.525430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08662492b43'
down_revision: Union[str, Sequence[str], None] = '215277700cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='app')
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'updated_at', schema='app')
    op.drop_column('products', 'created_at', schema='app')
    # ### end Alembic commands ###
